### ISSUE TITLE
Including this package breaks flutter web again

### ISSUE THREAD

**Issue by krille-chan** [canonical/dbus.dart#250]
Version 0.4.0 worked fine but the newest version again makes it impossible to build the flutter project on web.

```
[        ] Target dart2js failed: Exception: /root/.pub-cache/hosted/pub.dartlang.org/dbus-0.5.2/lib/src/dbus_value.dart:252:49:
           Error: The integer literal 9223372036854775807 can't be represented exactly in JavaScript.
               if (value < -9223372036854775808 || value > 9223372036854775807) {
                                                           ^^^^^^^^^^^^^^^^^^^
           Error: Compilation failed.
[   +1 ms] Compiling lib/main.dart for the Web... (completed in 11.0s)
[        ] "flutter web" took 15,526ms.
[   +2 ms] Exception: Failed to compile application for the Web.
[        ] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      buildWeb (package:flutter_tools/src/web/compile.dart:85:5)
           <asynchronous suspension>
           #2      BuildWebCommand.runCommand (package:flutter_tools/src/commands/build_web.dart:91:5)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1043:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
           <asynchronous suspension>
           #6      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
           <asynchronous suspension>
           #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
           <asynchronous suspension>
           #9      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #11     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>
[   +1 ms] ensureAnalyticsSent: 0ms
[        ] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
```

**Comment by proninyaroslav** [comment]
A similar problem  https://github.com/MaikuB/flutter_local_notifications/issues/1247#issuecomment-888299019

**Comment by proninyaroslav** [comment]
@ChristianPauly 
You can also use conditional imports:
```Dart
export 'src/use_dbus_stub.dart'
    if (dart.library.ffi) 'src/use_dbus_real.dart';
```

**Comment by jpnurmi** [comment]
@proninyaroslav Yes, that would be the way to go if you have control over it e.g. it's not an external dependency that pulls it in.

**Comment by proninyaroslav** [comment]
@jpnurmi 
In any case, `dbus` uses FFI which is not supported by the Web and there is no other solution but to make a similar stub in the `dbus` package itself.

**Comment by jpnurmi** [comment]
The FFI parts are stubbed: https://github.com/canonical/dbus.dart/blob/main/lib/src/getuid.dart
